apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-management
  labels:
    app: app-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-management
  template:
    metadata:
      labels:
        app: app-management
    spec:
      containers:
        - name: app-management
          image: thiare29/app-management:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
          resources:
            limits:
              cpu: 0.2
              memory: "200Mi"
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: mysql-user-password
            - name: DB_SERVER
              valueFrom:
                configMapKeyRef:
                  name:  mysql-config-map
                  key: mysql-server
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name:  mysql-config-map
                  key: mysql-database-name
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: mysql-user-username
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: app-management
  labels:
    app: app-management
spec:
  type: LoadBalancer
  selector:
    app: app-management
  ports:
    - protocol: TCP
      name: http
      port: 8081
      targetPort: 8081
      nodePort: 30001